### ISSUE TITLE
Faulty generation of markdown format for data type list

### ISSUE THREAD

**Issue by crazymind1337** [puppetlabs/puppet-strings#219]
## Describe the Bug
We are writing heavily custom data types to validate special hash formats. We are using `puppet strings generate --format markdown --out REFERENCES.md` for documentation. Our markdown-lint CI test complains about the `MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]`.

## Expected Behavior
Generating a markdown formated REFERENCES.md withtout `MD009/no-trailing-spaces` issues

## Steps to Reproduce
- write a module with a data type in it 
- add the documentation header to the data type file without `@summary ... `
- install markdown-lint:
  - npm install -g markdownlint-cli
  - npm install -g markdownlint
- execute the markdownlint:
  - node_modules/.bin/markdownlint <path_to_markdown_file>

## Environment
 - Version: 2.3.1
 - Platform: any (CI: ubuntu-18.04, local: MacOS 10.15.2)

## Additional Context
%

**Comment by eputnam** [comment]
@crazymind1337 , thanks for the issue!

Would you be able to share:
1. the documentation you have in your data type or even the module you're working on
2. the version of markdownlint you're using
3. whether or not you have a custom markdownlint config and what's custom about it

Those three things would go a long way in helping us look into the issue here.

**Comment by eputnam** [comment]
Hi @crazymind1337 , thanks for raising this issue. I haven't noticed any activity on this issue for a couple weeks so I'm going to close it for now. Please feel free to re-open!

**Comment by crazymind1337** [comment]
Ohh sorry,  didn't see your Comment.

markdownlint: 0.14.1
puppet-strings: 2.3.1

```puppet
# @summary 
#
#
class test_module () {}
```

```shell
$ puppet strings generate --format markdown --out REFERENCE.md
```

```shell
$ markdownlint REFERENCE.md
REFERENCE.md: 16: MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
```

**Comment by crazymind1337** [comment]
Also happens at:

```
#
#
class test_module () {}
```

```
REFERENCE.md: 8: MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
```

**Comment by crazymind1337** [comment]
@eputnam looks like I am no allowed to re-open the issue.

**Comment by binford2k** [comment]
```markdown
# Reference
<!-- DO NOT EDIT: This document was generated by Puppet Strings -->

## Table of Contents

**Classes**

* [`test_module`](#test_module): <-------- single trailing space

## Classes

### test_module

The test_module class.

```
