### ISSUE TITLE
Wrong enclosure for data type with multiple lines at markdown

### ISSUE THREAD

**Issue by crazymind1337** [puppetlabs/puppet-strings#223]
## Describe the Bug
If I add a data type with mutliple line, it will be enclosured with single "\`" (inline code section) instead of tripple "\`" (multi-line code fences). This causes a strange view at a markdownv viewer.

## Expected Behavior
It should be enclosed with ```\n<text>\n``` 

Expected result:
```markdown
Alias of

\```
Hash[Pattern[/^[a-z][a-z0-9_-]*$/], Struct[
    {
      param1 => String[1],
      param2 => Stdlib::Absolutepath,
      paramX => Boolean,
    }
  ]
]
\```
```

## Steps to Reproduce
1. add a custom data type, e.g.:
```puppet
# summary Test Type
#
type Test_module::Test_type = Hash[
  Pattern[/^[a-z][a-z0-9_-]*$/],
  Struct[
    {
      param1 => String[1],
      param2 => Stdlib::Absolutepath,
      paramX => Boolean,
    }
  ]
]
```
2. generate the REFERENCE.md:
```shell
puppet strings generate --format markdown --out REFERENCE.md
```
3. check the result, it will be like:
```markdown
Alias of `Hash[Pattern[/^[a-z][a-z0-9_-]*$/], Struct[
    {
      param1 => String[1],
      param2 => Stdlib::Absolutepath,
      paramX => Boolean,
    }
  ]]`
```

## Environment
 - Gem puppet-strings (2.3.1)
 - Platform MacOS 10.15.3 (19D76)

**Comment by binford2k** [comment]
To be clear, this generates markdown with inline code markup instead of code fences.

**Comment by binford2k** [comment]
I've reproduced this issue with the example case provided. Thanks for letting us know @crazymind1337!

**Comment by danielparks** [comment]
Looks like this is already in place for data type aliases, but it would be nice to extend that to default values and data types where we can. I have a branch that fixes this: https://github.com/danielparks/puppet-strings/compare/better_public_private...danielparks:puppet-strings:multiline_code_blocks (it’s waiting on PR #314, my unsubmitted fix for #240, and possibly [PUP-11632](https://tickets.puppetlabs.com/browse/PUP-11632)).

Also, thanks @crazymind1337, I was surprised that I couldn’t just use a multiline `Variant` type as a test case, so I used your example.

**Comment by danielparks** [comment]
Oh, I just figured out that I can link to a commit at the end of a branch without specifying the actual hash. Cool!

https://github.com/danielparks/puppet-strings/commit/multiline_code_blocks

**Comment by crazymind1337** [comment]
Thanks
