### ISSUE TITLE
Provider attribute is missing in generated types documentation

### ISSUE THREAD

**Issue by scotje** [puppetlabs/puppet-strings#227]
Add provider attribute to docs output.  This parameter is a base part of all types.  It does not show up in the documentation because it is defined in type.rb, instead of the individual type code files.

See also: https://tickets.puppetlabs.com/browse/PDOC-274

**Comment by binford2k** [comment]
Is this resolved in https://github.com/puppetlabs/puppet-strings/pull/231?

**Comment by DavidS** [comment]
Closing this as it apparently has already been done.
