### ISSUE TITLE
Add supported_features to puppet strings input/output for types

### ISSUE THREAD

**Issue by scotje** [puppetlabs/puppet-strings#228]
Need to ensure that the values for `supported_features` are output from strings when documenting types.

See also related issue: https://tickets.puppetlabs.com/browse/PUP-9451

**Comment by scotje** [comment]
@jbondpdx I looked at this a bit but I couldn't quite work out what was missing, let's go over it together next week.

**Comment by jbondpdx** [comment]
works for me, thank you!

**Comment by scotje** [comment]
Screenshot of missing content:

![unnamed](https://user-images.githubusercontent.com/9058/81436853-014c1b00-911f-11ea-8676-e73118004fb7.png)

**Comment by DavidS** [comment]
According to PUP-9451 this has been done.

**Comment by jbondpdx** [comment]
No, @DavidS ,  *required* features was added in that ticket. Supported features was not part of that work and Strings still doesn't pick it up.

**Comment by DavidS** [comment]
Thanks for clarifying!

**Comment by scotje** [comment]
OK, this turns out to have been an issue in the `puppet-docs` repo. Strings is already outputting this data as the `features` property of type providers.
