### ISSUE TITLE
`file` type is missing `ensure` in generated reference docs

### ISSUE THREAD

**Issue by jbondpdx** [puppetlabs/puppet-strings#230]
## Describe the Bug
In the generated Puppet types reference documentation, the `ensure` attribute is missing from the output for the `file` type.

## Expected Behavior
The `ensure` attribute, if it exists in the `file` type, should be present in the Strings output

1. Within the puppet-docs repo, run the internal docs generation command: `bundle exec rake references:puppet VERSION=6.14.0`
2. Diff the generated doc from puppet-docs/reference_output/puppet/types/file.md against the existing documentation in puppet-docs/source/puppet/latest/types/file.md

## Environment
cloned puppet-docs repo, *nix

## Additional Context
The generation command retrieves a vendored copy of the Puppet codebase; there's a setting you can change to have it use a Puppet codebase on your machine, if you need to test documentation changes sourced from the Puppet code itself. (I don't think this issue will require that, though.)

**Comment by DavidS** [comment]
1) I couldn't reproduce this, as the `references:puppet` rake task errored out on me:
```
Strings data: Done! (/home/david/git/puppet-docs/references_output/puppet/strings.json)
Type ref: Writing JSON as file
Type ref: Building unified page
Type ref: Building component
Type ref: Building exec
Type ref: Building file
Type ref: Building filebucket
Type ref: Building group
Type ref: Building notify
Type ref: Building package
Type ref: Building resources
Type ref: Building schedule
Type ref: Building service
Type ref: Building stage
Type ref: Building tidy
Type ref: Building user
Type ref: Building whit
Type ref: Done!
Functions ref (function.md): Building
rake aborted!
NoMethodError: undefined method `detect' for nil:NilClass
(erb):16:in `block (3 levels) in build_variant'
(erb):9:in `each'
(erb):9:in `each_with_index'
(erb):9:in `block (2 levels) in build_variant'
(erb):1:in `each'
(erb):1:in `block in build_variant'
/home/david/git/puppet-docs/lib/puppet_references/puppet/functions.rb:48:in `build_variant'
/home/david/git/puppet-docs/lib/puppet_references/puppet/functions.rb:21:in `build_all'
/home/david/git/puppet-docs/lib/puppet_references.rb:57:in `block in build_from_list_of_classes'
/home/david/git/puppet-docs/lib/puppet_references.rb:56:in `each'
/home/david/git/puppet-docs/lib/puppet_references.rb:56:in `build_from_list_of_classes'
/home/david/git/puppet-docs/lib/puppet_references.rb:42:in `build_puppet_references'
/home/david/git/puppet-docs/Rakefile:397:in `block (2 levels) in <top (required)>'
/home/david/gems/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => references:puppet
(See full trace by running task with --trace)
david@zion:~/git/puppet-docs (master)$
```
2) I'm about to release a new version from the current HEAD, please do retest with that
3) Please reduce the repro to the actual puppet-strings incantation, instead of a complicated process that also does clone repos, installs more gems and builds unrelated parts of the docs (like man pages), to make this easier to debug.

**Comment by jbondpdx** [comment]
@hestonhoffman , we should retest this with just Strings and see if it works. Let's coordinate about this?

**Comment by hestonhoffman** [comment]
I tested this earlier and the page looks good. Probable safe to close 👍

**Comment by DavidS** [comment]
Thank you!
