### ISSUE TITLE
Change to `main` primary branch

### ISSUE THREAD

**Issue by eputnam** [puppetlabs/puppet-strings#239]
## Use Case
When writing software, I want to do everything I can to be inclusive and not invoke slavery.

## Describe the Solution You Would Like
Get rid of `master` branch in favor of `main`

Apparently there's a [github cli](https://gist.github.com/mislav/5ac69530acbe1b4ca909e272caabfdba) and we can use that or do it the old fashioned way. Either way, we should find a way to help users make the change too.

## Describe Alternatives You've Considered
`trunk`, `primary`, `putnam`, `ericsCoolBranch`, `q`, `branchOfPower`

## Additional Context
[edit for additional context]
https://twitter.com/mislav/status/1270388510684598272
https://mail.gnome.org/archives/desktop-devel-list/2019-May/msg00066.html
https://blacklivesmatter.com/

**Comment by DavidS** [comment]
Apparently that's the solution github is converging to, too: https://twitter.com/billygriffin22/status/1271261076290539520 .

I'm happy to run this as an experiment on this repo first to see what other technical changes will be required to make this smooth. (e.g. appveyor/travis scheduled runs; release process/docs; etc)

**Comment by eputnam** [comment]
We left `master` but changed the default branch to `main`, which we created from a76dd4c30a7a4a29bd26ba29d7204912eebe8b81. We can leave this issue open in case there's any further discussion that needs to take place.

**Comment by DavidS** [comment]
@eputnam did you also update the [scheduled job](https://travis-ci.org/github/puppetlabs/puppet-strings/settings) on travis or did that follow the default branch automatically?

**Comment by scotje** [comment]
I updated it in Travis.

**Comment by scotje** [comment]
Going to close this issue now as these changes have been made and nothing seems to have exploded. Please feel free to re-open or open a new issue if something comes up.
