### ISSUE TITLE
text rendering as emojis in strings generated docs

### ISSUE THREAD

**Issue by wyardley** [puppetlabs/puppet-strings#242]
## Describe the Bug
Certain strings (e.g., .`erlang::repo::apt::erlang_solutions`) are rendered without being backtick escaped in certain places (headings, default values), and show up as emojis in rendered docs, as seen in 
thttps://github.com/voxpupuli/puppet-erlang/blob/master/REFERENCE.md

<img width="810" alt="image" src="https://user-images.githubusercontent.com/10714426/86309611-008cae00-bbd1-11ea-9c3f-37a8e980d6b6.png">

## Expected Behavior
The string is rendered without emojis

## Steps to Reproduce
1. Create documentation with a parameter that will produce an emoji (see examples)
2. Use Puppet strings to generate docs
3. ???
4. Profit

## Environment
 - n/a

## Additional Context
https://stackoverflow.com/questions/50657698/how-can-i-stop-github-from-rendering-emojis-in-markdown covers some of the possible workarounds. Wrapping in backticks should work.

**Comment by binford2k** [comment]
fixed in #243
