### ISSUE TITLE
Tags (Parameter, Returns) not generated in HTML output

### ISSUE THREAD

**Issue by raemer** [puppetlabs/puppet-strings#248]
## Describe the Bug
Descriptions from @params and @returns are missing in HTML output.

## Expected Behavior
Descriptions from @params and @returns should be visible in HTML output

## Steps to Reproduce
1. Document a (Ruby 4.x API) function and add @param and @returns tags.
2. Run puppet strings generate.

## Environment
 - Version 2.1.0

## Sources of Error and Fix
When adding support for @note and @todo, the yieldall-statement in overview moved from being the last entry, therefor it is not applied to the nesting any more. Moving @note and @todo into the nexting fixes this, I will add a pull request.

**Comment by scotje** [comment]
Resolved by #249
