### ISSUE TITLE
Please document the `author` tag

### ISSUE THREAD

**Issue by baurmatt** [puppetlabs/puppet-strings#256]
## Describe the Change You Would Like
@author was document in https://github.com/puppetlabs/puppet-strings/commit/56c24cc36247b61cf1ef32f9b464d014b62258fd but I can't find it in the documentation.

-> https://puppet.com/docs/puppet/6.18/puppet_strings.html#available-strings-tags

**Comment by DavidS** [comment]
I've pinged the docs team about this.

**Comment by sanfrancrisko** [comment]
This has now been added to the documentation.
