### ISSUE TITLE
`Public Functions` header shouldn't be output if there are only private functions

### ISSUE THREAD

**Issue by alexjfisher** [puppetlabs/puppet-strings#267]
## Describe the Bug
`Public Functions` header shouldn't be output if there are only private functions

## Expected Behavior
When a function is marked as `@api private` it appears under a `Private Functions` header instead of the generic `Functions` header.  If there are no public functions, the `Public Functions` header should be omitted.

See example and conversation [here](https://github.com/voxpupuli/puppet-chrony/pull/103/files#r552030356).

**Comment by danielparks** [comment]
This is also true for private resource types, and possibly other things as well.

**Comment by danielparks** [comment]
PR #314 submitted.

**Comment by danielparks** [comment]
Should be fixed now in main!
