### ISSUE TITLE
Lots of warnings about when running unit tests

### ISSUE THREAD

**Issue by danielparks** [puppetlabs/puppet-strings#302]
## Describe the Bug

Running `bundle exec rake spec` generates lots of warnings even though the tests run successfully.

Most of the warnings are about two calls to `ERB.new`. The unique warnings are:

> …/puppet-strings/lib/puppet-strings/markdown/table_of_contents.rb:21: warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments.
> …/puppet-strings/lib/puppet-strings/markdown/table_of_contents.rb:21: warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.
> …/puppet-strings/lib/puppet-strings/markdown/base.rb:186: warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments.
> …/puppet-strings/lib/puppet-strings/markdown/base.rb:186: warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.

There are also a bunch of “errors” that don’t result in test failures. They are all identical: (**Update:** I split this out into #307)

> \[error\]: Failed to parse (stdin): Syntax error at 'param1' (line: 5, column: 19)

I have tested this with Ruby 2.6.0p0 (not 2.3.0, see #301) and 3.1.2p20. In 2.6.0 the ERB warnings are not present, but the “ Failed to parse” messages are present in both.

## Expected Behavior

No extra output when running unit tests.

## Steps to Reproduce
1. `bundle exec rake spec`

## Environment
 - ruby 3.1.2p20
 - Current main branch (dba16eddabd4947f1901271648097b2f93aa13b5)

**Comment by danielparks** [comment]
After a bunch of testing, it looks like the parse error is at https://github.com/puppetlabs/puppet-strings/blob/dba16eddabd4947f1901271648097b2f93aa13b5/spec/unit/puppet-strings/json_spec.rb#L33

The ERB error, on the other hand, is easy to fix as long as the minimum ruby version is 2.6.0.

**Comment by danielparks** [comment]
I fixed the ERB error for all supported Ruby versions: https://github.com/puppetlabs/puppet-strings/compare/main...danielparks:puppet-strings:fix_erb

**Comment by chelnak** [comment]
Fixed in #302 - Thanks @danielparks
