### ISSUE TITLE
Document usage

### ISSUE THREAD

**Issue by spuder** [puppetlabs/puppet-strings#8]
The read me says that to install, you do the following: 

```
Currently, just git clone directly into the Puppet modulepath. Ensure the yard and rgen gems are installed. If running Ruby 1.8.7, ensure the backports gem is installed.
```

It would be if this was expounded on, so those those who don't know ruby well can get it installed. 

I know a little bit a ruby, but I'm still stumped as to how to get this going.

**Comment by binford2k** [comment]
This is now fairly well documented on https://puppet.com/docs/puppet/latest/puppet_strings.html
